Manipulação de Dados com Python e SQL [T7] - M1S10 - Mini Projeto Módulo 1 - 21/10/2026

Aluna: Isabela Gomes da Costa

DESAFIO:

 Desenvolver uma Análise Exploratória de Dados (AED) aplicada ao varejo para aprender como transformar dados brutos em informações úteis.

Link da Base de Dados: https://www.kaggle.com/datasets/namespaiva/base-varejo/data

- Sprint 1 (Importação dos dados)

In [6]:
# Importa o pandas para carregar, limpar e analisar os dados
%pip install pandas
import pandas as pd

Requirement already satisfied: pandas in c:\Users\isabe\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.6)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\isabe\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.5.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\isabe\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\isabe\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2026.5)
Requirement already satisfied: six>=1.5 in C:\Users\isabe\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.2.1 -> 26.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Para executar no VS Code, selecionar o kernel Python e usar **Executar Tudo**, com o CSV na mesma pasta do notebook. Caso o pandas não esteja instalado, executar `%pip install pandas` em uma célula separada, uma única vez.

In [10]:
# Carrega o arquivo CSV, que utiliza ponto e vírgula como separador
df_varejo = pd.read_csv("base_varejo.csv", sep=";")

# Exibe as primeiras cinco linhas da base
df_varejo.head()

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,NaN,NaN,NaN,NaN
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,NaN,NaN,NaN,NaN
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,NaN,NaN,NaN,NaN

- Sprint 2 (Transformação de Strings, Integer e Float e Datetime)

In [11]:
# Mostra a quantidade de registros e de colunas
print("Número de registros:", df_varejo.shape[0])
print("Número de colunas:", df_varejo.shape[1])

# Mostra os nomes das colunas
print("\nColunas da base:")
print(df_varejo.columns.tolist())

# Mostra o tipo de dado de cada coluna
print("\nTipos de dados:")
print(df_varejo.dtypes)

Número de registros: 830000
Número de colunas: 14

Colunas da base:
['DATA', 'CO_ID', 'CL_ID', 'CL_GENERO', 'CL_EC', 'CL_FHL', 'CL_SEG', 'PR_ID', 'PR_CAT', 'PR_NOME', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13']

Tipos de dados:
DATA               str
CO_ID            int64
CL_ID            int64
CL_GENERO          str
CL_EC            int64
CL_FHL           int64
CL_SEG             str
PR_ID            int64
PR_CAT             str
PR_NOME            str
Unnamed: 10    float64
Unnamed: 11    float64
Unnamed: 12    float64
Unnamed: 13    float64
dtype: object

Vemos que há 830000 registros e 14 colunas. Quatro delas possuem nomes como: Unnamed: 10, que já indicam um ponto de atenção que teremos que tratar no decorrer do desenvolvimento. Além disso, a coluna DATA foi carregada como texto, então será necessário convertê-la antes de analisar as compras ao longo do tempo.

Conforme o dicionário de dados disponibilizado no kaggle, CO_ID identifica a compra pelo número da nota fiscal, CL_ID identifica o cliente e PR_ID identifica o produto adquirido pelo seu SKU. Já PR_CAT informa a categoria do produto e PR_NOME, seu nome.

As características dos clientes estão nas colunas CL_GENERO, que representa o sexo biológico informado pelo cliente; CL_FHL, que informa o número de filhos; CL_SEG, que indica a classe econômica A, B ou C; e CL_EC, que representa o estado civil, com os códigos: 1 — casado ou união estável; 2 — divorciado; 3 — separado; 4 — solteiro; e 5 — viúvo.

Embora algumas dessas colunas contenham números, eles possuem funções diferentes. Os identificadores e os códigos de estado civil representam categorias, portanto calcular suas médias não teria significado para esta análise. O número de filhos, no entanto, é uma medida quantitativa e será utilizado nos cálculos estatísticos.

In [12]:
# Conta os valores ausentes em cada coluna
print("Valores nulos por coluna:")
print(df_varejo.isnull().sum())

Valores nulos por coluna:
DATA                0
CO_ID               0
CL_ID               0
CL_GENERO           0
CL_EC               0
CL_FHL              0
CL_SEG              0
PR_ID               0
PR_CAT              0
PR_NOME             0
Unnamed: 10    830000
Unnamed: 11    830000
Unnamed: 12    830000
Unnamed: 13    830000
dtype: int64

In [13]:
# Identifica linhas inteiramente iguais, contando as repetições após a primeira
duplicatas = df_varejo.duplicated()

print("Quantidade de registros duplicados:", duplicatas.sum())

# Exibe os registros identificados como repetidos
df_varejo[duplicatas]

Quantidade de registros duplicados: 96553

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
19,01/02/2019,1000,534,M,4,1,C,13,ALIMENTOS,BANANA,NaN,NaN,NaN,NaN
40,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
46,01/02/2019,1000,534,M,4,1,C,11,ALIMENTOS,AZEITE,NaN,NaN,NaN,NaN
49,01/02/2019,1000,534,M,4,1,C,69,BEBIDAS,REFRIGERANTE LIMaO,NaN,NaN,NaN,NaN
50,01/02/2019,1000,534,M,4,1,C,218,ALIMENTOS,BIFE DE COXAO MOLE,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
829989,19/08/2022,919822,155,F,2,0,B,34,ALIMENTOS,KETCHUP,NaN,NaN,NaN,NaN
829992,19/08/2022,919822,155,F,2,0,B,30,ALIMENTOS,FILE DE PEIXE,NaN,NaN,NaN,NaN
829995,19/08/2022,919822,155,F,2,0,B,183,ALIMENTOS,KETCHUP,NaN,NaN,NaN,NaN
829996,19/08/2022,919822,155,F,2,0,B,56,ALIMENTOS,QUEIJO MUSSARELA,NaN,NaN,NaN,NaN
829997,19/08/2022,919822,155,F,2,0,B,227,ALIMENTOS,ARROZ,NaN,NaN,NaN,NaN